// build.js — produces two extension builds from this folder (the single source).
//
//   dist/dev      Local + Hosted endpoint toggle (for development)
//   dist/release  Hosted endpoint only           (for the Chrome Web Store)
//
// Usage (from this folder):  node build.js
//        (from elsewhere):   node extension/build.js
//
// No dependencies — plain Node.js. The only per-channel differences are the
// generated channel.js flag and a few manifest tweaks; everything else is a
// straight copy of the source files.

const fs   = require("fs");
const path = require("path");

const SRC = __dirname;                       // the extension folder (this file lives here)
const OUT = path.join(__dirname, "dist");

const LOCAL_HOST = "http://127.0.0.1:5000/*";

// Top-level entries in this folder that are NOT part of the extension itself.
const EXCLUDE = new Set(["build.js", "dist", "node_modules", ".git", ".DS_Store"]);

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (src === SRC && EXCLUDE.has(entry.name)) continue; // skip build artifacts
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function build(channel) {
  const dest = path.join(OUT, channel);
  fs.rmSync(dest, { recursive: true, force: true });
  copyDir(SRC, dest);

  // 1. Bake the build channel.
  fs.writeFileSync(
    path.join(dest, "channel.js"),
    `// Generated by build.js — do not edit.\nself.CHANNEL = ${JSON.stringify(channel)};\n`
  );

  // 2. Tweak the manifest per channel.
  const manifestPath = path.join(dest, "manifest.json");
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

  if (channel === "release") {
    // Hosted only: drop the localhost host permission and the storage
    // permission (no endpoint toggle to persist) for a clean store review.
    manifest.host_permissions = manifest.host_permissions.filter(h => h !== LOCAL_HOST);
    manifest.permissions      = manifest.permissions.filter(p => p !== "storage");
  } else {
    // Make the dev build distinguishable when both are installed.
    manifest.name = manifest.name + " (Dev)";
  }

  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n");

  const rel = path.relative(path.join(__dirname, ".."), dest);
  console.log(`✓ ${channel.padEnd(7)} → ${rel}`);
  console.log(`    permissions:      ${manifest.permissions.join(", ")}`);
  console.log(`    host_permissions: ${manifest.host_permissions.join(", ")}`);
}

build("dev");
build("release");
console.log("\nDone. Load dist/dev or dist/release unpacked, or zip dist/release for the Web Store.");
